### ISSUE TITLE
gObjectClass_finalize errors on Linux32

### ISSUE THREAD

**Issue by Gord1** [Sloeber/arduino-eclipse-plugin#1033]
Using 32 bit Linux (Linux Mint 17.3) on older hardware and I keep getting this error box pop up every time I try and do something with latest version. 

'Open user dialog' has encountered a problem
An internal error has occurred.
gObjectClass_finalize

Using the latest Sloeber download package 4.3.2. Version 4.2 is OK.

My java version:
java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) Server VM (build 25.191-b12, mixed mode)

Seems like Eclipse has abandoned Linux32 and only tests and supports Linux64.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=527536
https://bugs.eclipse.org/bugs/show_bug.cgi?id=536766

Seems like Linux32 users are SOL so you should update your download page where you recommend that users us Linux32 version, unless you have a workaround.

Error Log below of an example.

Gordon Williams

-----------------------------------------------------------------------------------------------------------------------
From the error log:
eclipse.buildId=unknown
java.version=1.8.0_191
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86, WS=gtk, NL=en_CA
Framework arguments:  -perspective io.sloeber.application.perspective
Command-line arguments:  -os linux -ws gtk -arch x86 -perspective io.sloeber.application.perspective

org.eclipse.equinox.app
Error
Sat Oct 20 15:52:39 EDT 2018
Problems occurred when invoking code from plug-in: "org.eclipse.equinox.app".

java.lang.NoSuchMethodError: gObjectClass_finalize
	at org.eclipse.swt.internal.gtk.GTK._gtk_widget_destroy(Native Method)
	at org.eclipse.swt.internal.gtk.GTK.gtk_widget_destroy(GTK.java:8591)
	at org.eclipse.swt.widgets.Widget.destroyWidget(Widget.java:464)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1193)
	at org.eclipse.swt.widgets.Control.release(Control.java:4302)
	at org.eclipse.swt.widgets.Widget.dispose(Widget.java:499)
	at org.eclipse.swt.widgets.Shell.dispose(Shell.java:2740)
	at org.eclipse.swt.widgets.Shell.closeWidget(Shell.java:681)
	at org.eclipse.swt.widgets.Shell.close(Shell.java:676)
	at org.eclipse.ui.splash.AbstractSplashHandler.dispose(AbstractSplashHandler.java:63)
	at org.eclipse.ui.splash.BasicSplashHandler.dispose(BasicSplashHandler.java:163)
	at org.eclipse.ui.internal.Workbench$2$1.applicationRunning(Workbench.java:852)
	at org.eclipse.equinox.internal.app.EclipseAppHandle$1.run(EclipseAppHandle.java:268)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.applicationRunning(EclipseAppHandle.java:258)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1105)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)

**Comment by jantje** [comment]
>.....you should update your download page where you recommend that users us Linux32 version, unless you have a workaround.

I guess you are referring to
"If you are not sure take the 32 bit version. If the Arduino IDE is working on your system you have 32 bit java on your system and you are good to go. If you install the 64 bit version you also may have to install a 64 bit java."

**Comment by jantje** [comment]
And no I was not aware eclipse dropped 32 bit support.

**Comment by Gord1** [comment]
> I guess you are referring to

Yes, that was it.  

Also, maybe remove the link for Linux32 download for V4.3 as it doesn't work and make a link to V4.2 with a note that Eclipse doesn't support Linux32 so we are stuck at V4.2.

You can close issue when you want.

**Comment by Gord1** [comment]
**Maybe I'm wrong about Eclipse not supporting Linux32!!**

I was just on the Eclipse website and they have a Sept release for Eclipse for Linux32.  So I am confused.  Maybe they fixed the problems identified in the bugs.eclipse that I linked above.

Anyway, V4.3 has that bug and V4.2 works OK.

**Comment by jantje** [comment]
>Anyway, V4.3 has that bug and V4.2 works OK.

Strange V4.3 = (basically) V4.2+Italian. Must be a newer version somewhere pulled in by the build script.

**Comment by jantje** [comment]
Made a update to say use 64bit if you have a 64 bit system because eclipse stopped 32 bit support.
Tagged it wrongly as #1030 though

**Comment by jantje** [comment]
as the documentation has been updated I assume this issue can be closed

**Comment by HobbyDev1** [comment]
Hi, I was just happy still getting a 32Bit Version for Linux. After setup I ran in the same problem. So does it mean it won't work at all? If so, is the older version 4.2 still available? I downloaded the Beryllium version yesterday

Maybe these messages help if the problem I got is different:
- tones of messages like this:
(Sloeber, the Eclipse Arduino IDE:2599): GLib-CRITICAL **: 20:56:56.562: g_base64_encode_step: assertion 'in != NULL' failed

- at the end of the start up process I get these messages:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.bind.ReflectiveTypeAdapterFactory (file:/home/rainer/Downloads/plugins/com.google.gson_2.8.2.v20180104-1110.jar) to field java.io.File.path
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.bind.ReflectiveTypeAdapterFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
log4j:WARN No appenders could be found for logger (javax.jmdns.impl.JmDNSImpl).
log4j:WARN Please initialize the log4j system properly.
