### ISSUE TITLE
Create arduino/esp32 sketch fails

### ISSUE THREAD

**Issue by prgazevedo** [Sloeber/arduino-eclipse-plugin#1105]
**Describe the bug**
Hello

I just downloaded the latest Sloeber V4 IDE.
I have added the ESP32 Packager with window->preferences -> arduino -> platforms and boards ->esp32 -> esp32 -> 1.0.3

No problems here.

I create a new sketch.
I chose the esp32 /actually arduino UNO as well from the dropdown list as platform folder, fill in settings and click finish.

**To Reproduce**
Try to create a new sketch

**Expected behavior**
A new sketch ".ino"

**Screenshots**
See below

**Desktop (please complete the following information):**
 - OS: [OSX 10.14.6]
 - Browser [not relevant]
 - Version [not relevant]

**Additional context**
![image](https://user-images.githubusercontent.com/24637221/65693076-97897000-e06b-11e9-8943-7bf28dd96247.png)
![image](https://user-images.githubusercontent.com/24637221/65693213-d61f2a80-e06b-11e9-9b17-4ce19c5b1c25.png)

Log:
eclipse.buildId=unknown
java.version=1.8.0_111
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -perspective io.sloeber.application.perspective -perspective io.sloeber.application.perspective -keyring /Users/pedroazevedo/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -perspective io.sloeber.application.perspective -data file:/Users/pedroazevedo/Documents/sloeber-workspace/ -perspective io.sloeber.application.perspective -keyring /Users/pedroazevedo/.eclipse_keyring

io.sloeber.core.ui
Error
Thu Sep 26 14:42:36 WEST 2019
Failed to create project

Exception stack trace:
java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:445)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:352)
	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1034)
	at io.sloeber.ui.wizard.newsketch.NewSketchWizard.performFinish(NewSketchWizard.java:99)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:832)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:472)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4406)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4193)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3810)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.actions.NewWizardShortcutAction.run(NewWizardShortcutAction.java:130)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:412)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4406)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4193)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3810)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:633)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
Caused by: java.lang.NoSuchMethodError: org.eclipse.cdt.managedbuilder.internal.core.Configuration.<init>(Lorg/eclipse/cdt/managedbuilder/internal/core/ManagedProject;Lorg/eclipse/cdt/managedbuilder/internal/core/ToolChain;Ljava/lang/String;Ljava/lang/String;)V
	at io.sloeber.core.tools.ShouldHaveBeenInCDT.setCProjectDescription(ShouldHaveBeenInCDT.java:72)
	at io.sloeber.core.api.BoardDescriptor.createProject(BoardDescriptor.java:543)
	at io.sloeber.ui.wizard.newsketch.NewSketchWizard.createProjectWrapper(NewSketchWizard.java:127)
	at io.sloeber.ui.wizard.newsketch.NewSketchWizard$1.execute(NewSketchWizard.java:94)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.lambda$0(WorkspaceModifyOperation.java:110)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2322)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:131)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:436)
	... 51 more

**Comment by erdemuncuoglu** [comment]
This is a **duplicate** of #1073, #1090 and #1102.

Solution is [here](https://github.com/Sloeber/arduino-eclipse-plugin/issues/1102#issuecomment-527656989).
