### ISSUE TITLE
Release testing 4.4 Convert a Sloeber 3.3 project into a Sloeber 3.4 project [2] os:win environment variables are not cleaned up

### ISSUE THREAD

**Issue by jantje** [Sloeber/arduino-eclipse-plugin#1299]
After the upgrade
That didn't go well due to missing platforms and I have also seen issies of mylin in the logs
I got things to work but the environment variables from 3.3 are still there
![afbeelding](https://user-images.githubusercontent.com/1175841/107863825-848d6080-6e57-11eb-8637-2cadf3631c7c.png)

**Comment by jantje** [comment]
I think I found the root causr
In boarddesc this piece of code
```
    public boolean isValid() {
        if (myreferencingBoardsFile == null) {
            return false;
        }
        return myreferencingBoardsFile.exists();
```
is used to set the "clean the 3.3 environment variables flag" and "found a 3.3 config flag"
If the platform is not installed (which was my case) myreferencingBoardsFile will not exist and as sutch the conversion and the cleaning will not take place
I will need another test.

**Comment by jantje** [comment]
Seems like a file.delete calls the UI and this can lead to reentrancy 😕 
```

!ENTRY org.eclipse.jface 2 0 2021-02-14 02:59:30.477
!MESSAGE Ignored reentrant call while viewer is busy. This is only logged once per viewer instance, but similar calls will still be ignored.
!STACK 0
java.lang.RuntimeException
	at org.eclipse.jface.viewers.ColumnViewer.checkBusy(ColumnViewer.java:764)
	at org.eclipse.jface.viewers.AbstractTreeViewer.remove(AbstractTreeViewer.java:2240)
	at org.eclipse.ui.navigator.CommonViewer.remove(CommonViewer.java:326)
	at org.eclipse.ui.internal.navigator.resources.workbench.ResourceExtensionContentProvider.lambda$1(ResourceExtensionContentProvider.java:278)
	at org.eclipse.ui.internal.navigator.resources.workbench.ResourceExtensionContentProvider.runUpdates(ResourceExtensionContentProvider.java:307)
	at org.eclipse.ui.internal.navigator.resources.workbench.ResourceExtensionContentProvider.processDelta(ResourceExtensionContentProvider.java:132)
	at org.eclipse.ui.model.WorkbenchContentProvider.resourceChanged(WorkbenchContentProvider.java:103)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:305)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:295)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:158)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:380)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1502)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:786)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:727)
	at io.sloeber.core.api.SloeberProject.storeConfigurationFile(SloeberProject.java:748)
```

The root cause is probably me having deleted a file and the project still thinking it is there but still...
Why id the ui triggered for deleting a file
And if this is caused by broadcast changes, should they not be caught?
I mean, how is the code to know it is trigggered by a ui thing and the events of the delete will trigger the ui thing that is not reentrant?
