### ISSUE TITLE
Build failed on 2021/12/08

### ISSUE THREAD

**Issue by jantje** [Sloeber/arduino-eclipse-plugin#1418]
2 tests are failing
```

Tests run: 18, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 384.847 s <<< FAILURE! - in io.sloeber.core.NightlyJenkins
testExamples[00000_RTCZero:Library/RTCZero/Epoch:arduino_zero_edbg](io.sloeber.core.NightlyBoardPatronTest)  Time elapsed: 11.612 s
testExamples[00001_RTCZero:Library/RTCZero/SimpleRTC:arduino_zero_edbg](io.sloeber.core.NightlyBoardPatronTest)  Time elapsed: 9.66 s
testExamples[00002_RTCZero:Library/RTCZero/SimpleRTCAlarm:arduino_zero_edbg](io.sloeber.core.NightlyBoardPatronTest)  Time elapsed: 7.66 s
testExamples[00003_RTCZero:Library/RTCZero/SleepRTCAlarm:arduino_zero_edbg](io.sloeber.core.NightlyBoardPatronTest)  Time elapsed: 6.961 s
create_CPP_based_Sloeber_Project(io.sloeber.core.RegressionTest)  Time elapsed: 2.822 s
is_extern_C_taken_into_account(io.sloeber.core.RegressionTest)  Time elapsed: 3.429 s
are_defines_before_includes_taken_into_account(io.sloeber.core.RegressionTest)  Time elapsed: 2.902 s
issue1047_Board_Names_Can_Be_used_as_Strings(io.sloeber.core.RegressionTest)  Time elapsed: 41.444 s
openAndCloseUsesSavedSettings(io.sloeber.core.RegressionTest)  Time elapsed: 6.877 s
uploadPattern(io.sloeber.core.RegressionTest)  Time elapsed: 0.004 s  <<< FAILURE!
org.junit.ComparisonFailure: ESP OTA upload recipe key is wrong expected:<tools.[esptool_py].upload.network_patt...> but was:<tools.[].upload.network_patt...>
	at io.sloeber.core.RegressionTest.uploadPattern(RegressionTest.java:586)

issue555(io.sloeber.core.RegressionTest)  Time elapsed: 6.789 s  <<< FAILURE!
java.lang.AssertionError: Failed to compile the project:issue555 as teensy
	at io.sloeber.core.RegressionTest.issue555(RegressionTest.java:123)
```

The test issue555 should not be run on the build server as it uses teensy to compile and I can't install teensy using the boardsmanager.
This is a regression because I simplified the System class to get going and need to add some complexity again.

I'm not sure why uploadPattern fails as it runs fine from within eclipse windows..

**Comment by jantje** [comment]
Seems uploadPattern  worked this time.
I'll assume it was a glitch
