### ISSUE TITLE
add gnu ARM open ocd debug launch

### ISSUE THREAD

**Issue by jantje** [Sloeber/arduino-eclipse-plugin#603]
To have everything installed in Sloeber to do debugging of the zero following 2 features need to be added:
```
GNU ARM C/C++ Cross Compiler

Version: 2.2.1.201606210758
Build id: @build@

Copyright (c) Liviu Ionescu 2009-2014.  All rights reserved.

This plug-in is part of the GNU ARM Eclipse plug-ins project.
For more details, visit <http://gnuarmeclipse.github.io>.
For updates, use <http://gnuarmeclipse.sourceforge.net/updates>.
```

```
GNU ARM C/C++ OpenOCD Debugging

Version: 4.1.1.201606210758
Build id: @build@

Copyright (c) Liviu Ionescu 2009-2014.  All rights reserved.

This plug-in is part of the GNU ARM Eclipse plug-ins project.
For more details, visit <http://gnuarmeclipse.github.io>.
For updates, use <http://gnuarmeclipse.sourceforge.net/updates>.
```

**Comment by wimjongman** [comment]
The site [1] does not seem to be valid. I cannot retrieve the repo from that location.

[1] http://gnuarmeclipse.sourceforge.net/updates

Can anyone try to access it from withing Eclipse by adding it as an update site?

![image](https://cloud.githubusercontent.com/assets/180969/21314969/291adb74-c5fa-11e6-8486-acb607c24c12.png)


eclipse.buildId=4.7.0.I20161208-0830
java.version=1.8.0_91
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.committers.product -clearpersistedstate
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.committers.product -clean -clearpersistedstate

org.eclipse.equinox.p2.transport.ecf
Warning
Mon Dec 19 14:28:16 CET 2016
Connection to http://gnuarmeclipse.sourceforge.net/updates/p2.index failed on sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target. Retry attempt 0 started

javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.writeRecord(Unknown Source)
	at sun.security.ssl.AppOutputStream.write(Unknown Source)
	at org.apache.http.impl.io.AbstractSessionOutputBuffer.flushBuffer(AbstractSessionOutputBuffer.java:159)
	at org.apache.http.impl.io.AbstractSessionOutputBuffer.flush(AbstractSessionOutputBuffer.java:166)
	at org.apache.http.impl.AbstractHttpClientConnection.doFlush(AbstractHttpClientConnection.java:272)
	at org.apache.http.impl.AbstractHttpClientConnection.flush(AbstractHttpClientConnection.java:277)
	at org.apache.http.impl.conn.AbstractClientConnAdapter.flush(AbstractClientConnAdapter.java:201)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:239)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer.performConnect(HttpClientRetrieveFileTransfer.java:1084)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer.access$0(HttpClientRetrieveFileTransfer.java:1075)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer$1.performFileTransfer(HttpClientRetrieveFileTransfer.java:1071)
	at org.eclipse.ecf.filetransfer.FileTransferJob.run(FileTransferJob.java:74)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at sun.security.validator.Validator.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 24 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.security.cert.CertPathBuilder.build(Unknown Source)
	... 30 more

**Comment by jantje** [comment]
works with me.
Maybe it was a glitch?
![capture](https://cloud.githubusercontent.com/assets/1175841/21317637/3dc9a3f0-c606-11e6-9b36-232bc378f527.PNG)

**Comment by jantje** [comment]
de nightly build failed with the sourceforge update site as error
Just relaunched it.

**Comment by jantje** [comment]
Keeps on  failing
IMHO using sourceforge as download site is just not working properly
I see similar problems with json files with board definitions
```
[INFO] Fetching p2.index from http://download.eclipse.org/releases/neon/201609281000/ (0B at 0B/s)

[INFO] Fetching p2.index from http://download.eclipse.org/releases/neon/201610111000/ (0B at 0B/s)

[INFO] Adding repository http://download.eclipse.org/nebula/snapshot

[WARNING] Invalid cookie header: "Set-Cookie: VISITOR=58593fe0cc0a456dcc5d3bd8; expires="Fri, 18-Dec-2026 14:27:44 GMT"; httponly; Max-Age=315360000; Path=/". Unable to parse expires attribute: "Fri, 18-Dec-2026 14:27:44 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: VISITOR=58593fe0cc0a456dcc5d3bd8; expires="Fri, 18-Dec-2026 14:27:45 GMT"; httponly; Max-Age=315360000; Path=/". Unable to parse expires attribute: "Fri, 18-Dec-2026 14:27:45 GMT"

[WARNING] Invalid cookie header: "Set-Cookie: VISITOR=58593fe0cc0a456dcc5d3bd8; expires="Fri, 18-Dec-2026 14:27:45 GMT"; httponly; Max-Age=315360000; Path=/". Unable to parse expires attribute: "Fri, 18-Dec-2026 14:27:45 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: sf_mirror_attempt="gnuarmeclipse:freefr:Eclipse/updates/p2.index"; expires=120; Path=/". Unable to parse expires attribute: 120

[WARNING] Invalid cookie header: "Set-Cookie: VISITOR=58593fe3bf503f395370e4c9; expires="Fri, 18-Dec-2026 14:27:47 GMT"; httponly; Max-Age=315360000; Path=/". Unable to parse expires attribute: "Fri, 18-Dec-2026 14:27:47 GMT"

[WARNING] Invalid cookie header: "Set-Cookie: VISITOR=58593fe3bf503f395370e4c9; expires="Fri, 18-Dec-2026 14:27:47 GMT"; httponly; Max-Age=315360000; Path=/". Unable to parse expires attribute: "Fri, 18-Dec-2026 14:27:47 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: VISITOR=58593fe3bf503f395370e4c9; expires="Fri, 18-Dec-2026 14:27:48 GMT"; httponly; Max-Age=315360000; Path=/". Unable to parse expires attribute: "Fri, 18-Dec-2026 14:27:48 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: sf_mirror_attempt="gnuarmeclipse:heanet:Eclipse/updates/p2.index"; expires=120; Path=/". Unable to parse expires attribute: 120
[INFO] Adding repository http://gnuarmeclipse.sourceforge.net/updates

[WARNING] Invalid cookie header: "Set-Cookie: VISITOR=58593fe6cc0a456dce307f3b; expires="Fri, 18-Dec-2026 14:27:50 GMT"; httponly; Max-Age=315360000; Path=/". Unable to parse expires attribute: "Fri, 18-Dec-2026 14:27:50 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: VISITOR=58593fe6cc0a456dce307f3b; expires="Fri, 18-Dec-2026 14:27:50 GMT"; httponly; Max-Age=315360000; Path=/". Unable to parse expires attribute: "Fri, 18-Dec-2026 14:27:50 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: sf_mirror_attempt="gnuarmeclipse:netix:Eclipse/updates/content.jar"; expires=120; Path=/". Unable to parse expires attribute: 120

[WARNING] Invalid cookie header: "Set-Cookie: webflash=; expires="Thu, 15-Dec-2016 14:27:52 GMT"; Max-Age=0; Path=/". Unable to parse expires attribute: "Thu, 15-Dec-2016 14:27:52 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: webflash=; expires="Thu, 15-Dec-2016 14:27:52 GMT"; Max-Age=0; Path=/". Unable to parse expires attribute: "Thu, 15-Dec-2016 14:27:52 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: webflash=; expires="Thu, 15-Dec-2016 14:27:52 GMT"; Max-Age=0; Path=/". Unable to parse expires attribute: "Thu, 15-Dec-2016 14:27:52 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: webflash=; expires="Thu, 15-Dec-2016 14:27:52 GMT"; Max-Age=0; Path=/". Unable to parse expires attribute: "Thu, 15-Dec-2016 14:27:52 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: VISITOR=58593fe80b4738274d05cc54; expires="Fri, 18-Dec-2026 14:27:52 GMT"; httponly; Max-Age=315360000; Path=/". Unable to parse expires attribute: "Fri, 18-Dec-2026 14:27:52 GMT"

[WARNING] Invalid cookie header: "Set-Cookie: VISITOR=58593fe9ebbb923273706d8b; expires="Fri, 18-Dec-2026 14:27:53 GMT"; httponly; Max-Age=315360000; Path=/". Unable to parse expires attribute: "Fri, 18-Dec-2026 14:27:53 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: VISITOR=58593fe9ebbb923273706d8b; expires="Fri, 18-Dec-2026 14:27:54 GMT"; httponly; Max-Age=315360000; Path=/". Unable to parse expires attribute: "Fri, 18-Dec-2026 14:27:54 GMT"

[WARNING] Invalid cookie header: "Set-Cookie: VISITOR=58593fe9ebbb923273706d8b; expires="Fri, 18-Dec-2026 14:27:54 GMT"; httponly; Max-Age=315360000; Path=/". Unable to parse expires attribute: "Fri, 18-Dec-2026 14:27:54 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: sf_mirror_attempt="gnuarmeclipse:netix:Eclipse/updates/content.xml.xz"; expires=120; Path=/". Unable to parse expires attribute: 120

[WARNING] Invalid cookie header: "Set-Cookie: webflash=; expires="Thu, 15-Dec-2016 14:27:56 GMT"; Max-Age=0; Path=/". Unable to parse expires attribute: "Thu, 15-Dec-2016 14:27:56 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: webflash=; expires="Thu, 15-Dec-2016 14:27:56 GMT"; Max-Age=0; Path=/". Unable to parse expires attribute: "Thu, 15-Dec-2016 14:27:56 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: webflash=; expires="Thu, 15-Dec-2016 14:27:56 GMT"; Max-Age=0; Path=/". Unable to parse expires attribute: "Thu, 15-Dec-2016 14:27:56 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: webflash=; expires="Thu, 15-Dec-2016 14:27:56 GMT"; Max-Age=0; Path=/". Unable to parse expires attribute: "Thu, 15-Dec-2016 14:27:56 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: VISITOR=58593fecedb41151fe05ac31; expires="Fri, 18-Dec-2026 14:27:56 GMT"; httponly; Max-Age=315360000; Path=/". Unable to parse expires attribute: "Fri, 18-Dec-2026 14:27:56 GMT"

[WARNING] Invalid cookie header: "Set-Cookie: webflash=; expires="Thu, 15-Dec-2016 14:27:57 GMT"; Max-Age=0; Path=/". Unable to parse expires attribute: "Thu, 15-Dec-2016 14:27:57 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: webflash=; expires="Thu, 15-Dec-2016 14:27:57 GMT"; Max-Age=0; Path=/". Unable to parse expires attribute: "Thu, 15-Dec-2016 14:27:57 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: webflash=; expires="Thu, 15-Dec-2016 14:27:57 GMT"; Max-Age=0; Path=/". Unable to parse expires attribute: "Thu, 15-Dec-2016 14:27:57 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: webflash=; expires="Thu, 15-Dec-2016 14:27:57 GMT"; Max-Age=0; Path=/". Unable to parse expires attribute: "Thu, 15-Dec-2016 14:27:57 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: VISITOR=58593feddab0ca3fa5e90ffa; expires="Fri, 18-Dec-2026 14:27:57 GMT"; httponly; Max-Age=315360000; Path=/". Unable to parse expires attribute: "Fri, 18-Dec-2026 14:27:57 GMT"

[WARNING] Invalid cookie header: "Set-Cookie: webflash=; expires="Thu, 15-Dec-2016 14:27:58 GMT"; Max-Age=0; Path=/". Unable to parse expires attribute: "Thu, 15-Dec-2016 14:27:58 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: webflash=; expires="Thu, 15-Dec-2016 14:27:58 GMT"; Max-Age=0; Path=/". Unable to parse expires attribute: "Thu, 15-Dec-2016 14:27:58 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: webflash=; expires="Thu, 15-Dec-2016 14:27:58 GMT"; Max-Age=0; Path=/". Unable to parse expires attribute: "Thu, 15-Dec-2016 14:27:58 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: webflash=; expires="Thu, 15-Dec-2016 14:27:58 GMT"; Max-Age=0; Path=/". Unable to parse expires attribute: "Thu, 15-Dec-2016 14:27:58 GMT"
[WARNING] Invalid cookie header: "Set-Cookie: VISITOR=58593feeeeac0f33a5927c4e; expires="Fri, 18-Dec-2026 14:27:58 GMT"; httponly; Max-Age=315360000; Path=/". Unable to parse expires attribute: "Fri, 18-Dec-2026 14:27:58 GMT"
[ERROR] Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'gnuarm' from location http://gnuarmeclipse.sourceforge.net/updates: No repository found at http://gnuarmeclipse.sourceforge.net/updates. -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'gnuarm' from location http://gnuarmeclipse.sourceforge.net/updates
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:167)
	at org.jvnet.hudson.maven3.launcher.Maven32Launcher.main(Maven32Launcher.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at jenkins.maven3.agent.Maven32Main.launch(Maven32Main.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:136)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:71)
	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failed to load p2 repository with ID 'gnuarm' from location http://gnuarmeclipse.sourceforge.net/updates
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.loadMetadataRepository(TargetPlatformFactoryImpl.java:302)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.gatherExternalInstallableUnits(TargetPlatformFactoryImpl.java:270)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:176)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:128)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:1)
	at org.eclipse.tycho.p2.manager.ReactorRepositoryManagerImpl.computePreliminaryTargetPlatform(ReactorRepositoryManagerImpl.java:84)
	at org.eclipse.tycho.p2.resolver.P2DependencyResolver.computePreliminaryTargetPlatform(P2DependencyResolver.java:223)
	at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:109)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:95)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	... 22 more
Caused by: org.eclipse.equinox.p2.core.ProvisionException: No repository found at http://gnuarmeclipse.sourceforge.net/updates.
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:395)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:692)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
	at org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager.loadRepository(RemoteMetadataRepositoryManager.java:61)
	at org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager.loadRepository(RemoteMetadataRepositoryManager.java:53)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.loadMetadataRepository(TargetPlatformFactoryImpl.java:298)
	... 32 more
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
channel stopped
[workspace] $ /bin/bash /share/CACHEDEV1_DATA/.qpkg/Tomcat/tomcat/temp/CommandInterpreterCondition6377758392693734658.sh
commit d6af56333c61e7e7a41e2c4c0431a6b65ce78003
change
Run condition [Execute Shell] enabling perform for step [[Send build artifacts over FTP]]
FTP: Current build result is [FAILURE], not going to run.
Sending e-mails to: eclipse@baeyens.it

ERROR: Invalid Addresses
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 554 5.7.1 Recipient address rejected: Username jan@baeyens.it and sender nobody@nowhere doesnt match

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1835)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1098)
	at javax.mail.Transport.send0(Transport.java:195)
	at javax.mail.Transport.send(Transport.java:124)
	at hudson.tasks.MailSender.run(MailSender.java:128)
	at hudson.tasks.MailSender.execute(MailSender.java:103)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.cleanUp(MavenModuleSetBuild.java:1065)
	at hudson.model.Run.execute(Run.java:1785)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:531)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 554 5.7.1 Recipient address rejected: Username jan@baeyens.it and sender nobody@nowhere doesnt match

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1733)
	... 10 more
Finished: FAILURE

```

**Comment by llemtt** [comment]
http://gnuarmeclipse.sourceforge.net/updates doesn't work for me either, I usually download the repository zip and install locally, it works!

**Comment by jantje** [comment]
Now there is a copy on sloeber and sloeber uses that copy it should be all fine

**Comment by ArmandoMobileVoid** [comment]
Getting the exact same error trying to install GNU ARM Eclipse plugin, tried yesterday with the same problem.

I installed some other plugin to day from source forge and it worked ...so believe its is related to this plugin.



[GNU ARM Wont install.pdf](https://github.com/jantje/arduino-eclipse-plugin/files/690575/GNU.ARM.Wont.install.pdf)

**Comment by jantje** [comment]
Apparently you need the very latest jdk or work around by using this update site http://sloeber.io/gnuarmeclipse/stable

**Comment by ArmandoMobileVoid** [comment]
Believe the issue was something in Eclipse V 4.4 just would not find it in sourceforge, I installed Mars and it installed fine...(but it did leave off a few things unchecked....). I had the latest idk....installed it before I tried to get this other stuff working. Thanks for the help!
