### ISSUE TITLE
upload of atTiny85 fails

### ISSUE THREAD

**Issue by jantje** [Sloeber/arduino-eclipse-plugin#808]
json file used: http://www.leonardomiliani.com/repository/package_leonardomiliani.com_index.json.
stack trace
```
java.io.IOException: Cannot run program "ARDUINO:ARDUINOISP" (in directory "D:\workspaces\embedded"): CreateProcess error=2, Het systeem kan het opgegeven bestand niet vinden
	at java.lang.ProcessBuilder.start(Unknown Source)
	at io.sloeber.core.tools.ExternalCommandLauncher.launch(ExternalCommandLauncher.java:294)
	at io.sloeber.core.tools.uploaders.GenericLocalUploader.RunConsoledCommand(GenericLocalUploader.java:42)
	at io.sloeber.core.tools.uploaders.arduinoUploader.uploadUsingPreferences(arduinoUploader.java:87)
	at io.sloeber.core.tools.uploaders.UploadSketchWrapper$UploadJobWrapper.run(UploadSketchWrapper.java:178)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.io.IOException: CreateProcess error=2, Het systeem kan het opgegeven bestand niet vinden
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 6 more
```
Arduino properties:
![afbeelding](https://user-images.githubusercontent.com/1175841/30033506-f3973204-919b-11e7-9c6c-981139505adc.png)

**Comment by jantje** [comment]
This board references arduinoISP which is in the programmers.txt file.
Currently the programmers.txt file is not processed by sloeber.
But if the uploader is referencing a platform it is logical the programmers.txt of this platform is processed.

**Comment by jantje** [comment]
I got this working as far as I think I should go. You  needs to select the programmer but this platformcomes with a old(?) avrdude that does not know the arduinoISP protocol.
